"""empty message

Revision ID: 75831c9f0c69
Revises: 121466cafa9a
Create Date: 2023-08-21 19:01:54.368206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75831c9f0c69'
down_revision = '121466cafa9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
